services:
  api:
    build: .
    ports:
      - 4000:3000
      - 4001:3001
    environment:
      MONGO_URL: mongodb://root:example@mongo:27017
      REFEASH_DELAY_MS: 2000
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
