services:
  api:
    build: .
    ports:
      - 4000:3000
      - 4001:3001
    environment:
      MONGO_URL: mongodb://root:example@mongo:27017
      REFEASH_DELAY_MS: 2000
      RESERVATION_SERVICE_URL: http://host.docker.internal:9000
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  envoy:
    image: envoyproxy/envoy:v1.28.0
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    ports:
      - 8080:8080
      - 9901:9901
